apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:11NmLx6BaVq+X89/XSog7+gz24DEEx3WPTLek1Cl8eq0KrbXh8jO2yNpyWfEG+z/EPw0oDTqjelpJTSx3NUPgvZoscrLMTQ0vTfYkDVfyJ83VJaoNnY+1dTLdjb8Dz1UhlI862h9GNEV28QB578l5uZT1YpyF2ldH83Crh8+jN2u392iKqSQHbOEpzprWBl+ecBqoLhXczSMAJYbIeT6l2izCXHEwh6JD9RQHaizvrFeXPkGxgmnqUd6VhNt6HJtKnrAVvvVVe1QD9kklvecz/PliPVCAGQFlt3gKr6tzubHDc+YcArEqQpy4E0eyAkJS0ogtcagCZcZQMCvLhfqGtKMjo8+tfK0gb9chDQOgqBnXo7QaghUI6muKqclPD9F,iv:RRXqUkU1aqZdjl30Uv4nesHd9i8NoWFV2fOgGSALkaM=,tag:e2mpltT3I5voekOm7tX5lQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:sUDvmeFZ00p9MDVCRHSJO/iPZaPCpWZ1KVA0HRHISBpxbXmuteNW4o1ETcC8Bx/lDIy0frJyGMWiYo0YdV2ajwOoRQs+cyNxkVhysfXH5jxZJJ2HTiwaZQdgxZshF3fSPAfIRA+yLcjpApJg5vwht2HvsqANrbgRTEIfwB1FqG7laxKFUo/R4T0s3fVDSEyS35w/DLtC/M78Ze4MRQHltum8LBL0BwCWTPsZjk0jh+FuNKvJAXXzRph9g6PCOZjmqz2Y1VSQvkrkdStNLQ==,iv:/eZLTXeMo5falfmw3OyWtKsKj43V5lWZCGjAtSV7fTA=,tag:Qhrvl8fEcns5mPi5nWVNFg==,type:str]
    known_hosts: ENC[AES256_GCM,data:XizUKkLapVEh3tJPnvt0op9KuWC+FJ07ambvnBMgrLrvGthpyOp0q4U0CI4iKSbMpsBBtZY2XDL/Vaminn4Xfbxot5Jg9SGWYgzibscsoYuvMGaP+iVnFIhlwgeG+jLDo3UtJ/X7Uc/gSNfqQafR/ZEID00SEuHptK6tHFsJAOTjTg0cvfI32KKzgouuFvg4BRnSNiYNpn7hSD6CLpC+7+Ae2zFZ4nA6Ah3C,iv:yDTUBv1xx6NSeYT/vUiZi3EcC9i3qjLbGL5feDsFJks=,tag:Mo0qTbY9r+1UKX5XFFuvPQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1eg8vye9neawjlkmnxugs6gazd2qect88puj2ty6wuj7h433ra9js50c5kn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwQmZnWTdVWEFWNG1rb1lG
            ZzlMZDBWYWt2U3BzaDFSRFRtZm1raU1US0N3CnJWQk13T1BFelVPTFo5RGlEeVht
            aFIrZzVKZkt0YzMvcUxEMnhidVBtRHcKLS0tIDFVcjRKZHhWUHd3MGR5alhBOGho
            VHlOVkp3ZW93RUh3MzZqVHZoTGdXSVEKGVHsr7go59hf3zl1OniJLTJd4JFyiev6
            bg1AdUBOiW7QL/+8U4aYrbFjGAE0x37nGXnSj/WtSB0zZOThGJRT7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-05T16:04:07Z"
    mac: ENC[AES256_GCM,data:FBC0Q1asEbUlWHISdszZLlQr2CRra1LJlgrFHfDpRrA95cQN3f2m6Y9GiLeI3ILrqNmZLySj1DegWwxPA7wrqRps+Np80GcN0hQonPbfdNyy8Afd0qnZLLUHRaQk7DxH7r94hnBs8FnN3VdgnvgEMZJCZjxUhASSjUxAf0DXx7s=,iv:mLX9wphvqVVg6VKqsfpoRO6bfF8OSnNxn9QXNS9KWb4=,tag:kBYn2EoaPxH+hS7GFZHG5A==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
